name: online_learning_app
description: Online Learning App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_test:
    sdk: flutter
  bot_toast: ^4.1.3
  flutter_spinkit: ^5.2.0 # A collection of loading indicators animated with flutter.
  flutter_svg: ^2.0.7
  smooth_page_indicator:
    git: https://github.com/dimashimko/smooth_page_indicator
  range_slider_flutter:
    git: https://github.com/haptome/flutter_range_slide
  dio: ^5.3.0
  easy_localization: ^3.0.2
  flutter_bloc: ^8.0.3
  hive_flutter: ^1.1.0
  jwt_decoder: ^2.0.1
  path_provider: ^2.0.15
  pretty_dio_logger: ^1.3.1
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  cloud_firestore: ^4.8.3
  pin_code_fields: ^8.0.1
  google_sign_in: ^6.1.4
  flutter_facebook_auth: ^6.0.0
  email_validator: ^2.1.17
  change_app_package_name: ^1.1.0
  appinio_video_player: ^1.2.2
  jiffy: ^6.2.1
  equatable: ^2.0.5
  share: ^2.0.4
#  share_plus: ^7.1.0
  flutter_secure_storage: ^9.0.0
  flutter_credit_card: ^3.0.3
  http: ^1.0.0
  liqpay:
    git:
#      url: https://github.com/dimashimko/liqpay
      url: https://github.com/Newgarden-Solutions/liqpay
      ref: main
  uuid: ^3.0.6


flutter_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  ios: true


dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  #Подключение иконок, фотографий, переводов и т.д.
  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/

  #Шрифты под разный тип жирности (Можно увидеть в resources > AppFonts)
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800



