name: online_learning_app
description: Online Learning App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #  Firebase
  firebase_analytics: ^10.5.0
  firebase_crashlytics: ^3.3.6
  firebase_storage: ^11.0.9
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  cloud_firestore: ^4.8.3

  #  Localization
  easy_localization: ^3.0.2

  # Navigation

  # Storage
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # Models
  equatable: ^2.0.5

  # State manager
  flutter_bloc: ^8.0.3
  provider: ^6.0.5

  # Media
  appinio_video_player: ^1.2.2

  # Notification
  bot_toast: ^4.1.3
  flutter_local_notifications: ^16.1.0

  # Auth
  google_sign_in: ^6.1.4
  flutter_facebook_auth: ^6.0.0
  email_validator: ^2.1.17
  pin_code_fields: ^8.0.1


  # Widgets
  flutter_svg: ^2.0.7
  smooth_page_indicator:
    git: https://github.com/dimashimko/smooth_page_indicator
  flutter_credit_card: ^3.0.3

  # Network
  connectivity_plus: ^5.0.1
  url_launcher: ^6.1.11
  http: ^1.1.0
  liqpay:
    git:
      url: https://github.com/dimashimko/liqpay
      ref: a3ac2e86622164a3d963fbb9bf4c30d19f55cd5e # commit hash

  # Utils
  jiffy: ^6.2.1
  image_picker: ^1.0.4
  uuid: ^3.0.6
  share: ^2.0.4
  infinite_scroll_pagination: ^4.0.0

flutter_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  ios: true


dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800



